# Pytorch Basics

https://colab.research.google.com/drive/1eiUBpmQ4m7Lbxqi2xth1jBaL61XTKdxp?usp=sharing#scrollTo=V2uQnrUpw8DA

In [2]:
import torch
import numpy as np

# List

In [3]:
list1=[[1,2,3,4,5],[6,7,8,9,10]]
list1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
npl = np.random.rand(3,4)
npl

array([[0.12748479, 0.08902439, 0.92354496, 0.09509523],
       [0.26407822, 0.66976059, 0.92347688, 0.4790156 ],
       [0.80244146, 0.7972801 , 0.85553681, 0.19363493]])

In [5]:
npl.dtype

dtype('float64')

Reshape and view are used to reshape 

2D

In [6]:
tensor_l = torch.randn(3,4)
tensor_l

tensor([[-1.7112, -0.5155,  0.8893,  1.2086],
        [ 0.5436,  0.1011, -1.1752, -0.5057],
        [ 0.9918,  3.9866, -0.7817, -0.5855]])

3d

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

create tensor out of numpy array

In [8]:
my_tensor = torch.tensor(npl)
my_tensor

tensor([[0.1275, 0.0890, 0.9235, 0.0951],
        [0.2641, 0.6698, 0.9235, 0.4790],
        [0.8024, 0.7973, 0.8555, 0.1936]], dtype=torch.float64)

Reshape and View

In [9]:
my_torch1 = torch.arange(10)
my_torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch1 = my_torch1.reshape(2,5)
my_torch1.dtype

torch.int64

In [10]:
my_torch2 = torch.arange(10)

In [11]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch3 = torch.arange(10)
my_torch3 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch4 = my_torch3.reshape(2,5)

In [14]:
# Difference btw reshape and view 

In [15]:
my_torch5 = torch.arange(10)

In [16]:
my_torch6 = my_torch5.reshape(2,5)

In [17]:
my_torch5[1]=4114

In [18]:
my_torch5

tensor([   0, 4114,    2,    3,    4,    5,    6,    7,    8,    9])

In [19]:
# Slices

In [20]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# grab a specific item
my_torch7[7]

tensor(7)

In [22]:
# grab slice 
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Mathematical Operations 



In [25]:
# tensor 

In [26]:
ten_a = torch.tensor([1,2,3,4])
ten_b = torch.tensor([5,6,7,8])

In [27]:
ten_a + ten_b

tensor([ 6,  8, 10, 12])

In [28]:
torch.add(tensor_a,tensor_b)

NameError: name 'tensor_a' is not defined

In [ ]:
torch.sub(ten_a,ten_b)

tensor([-4, -4, -4, -4])

In [ ]:
torch.mul(ten_a,ten_b)

tensor([ 5, 12, 21, 32])

In [ ]:
torch.div(ten_a,ten_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
torch.remainder(ten_a,ten_b)

tensor([1, 2, 3, 4])

In [ ]:
torch.pow(ten_a,ten_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
ten_a.add_(ten_b)

tensor([ 6,  8, 10, 12])