In [1]:
import torch

In [4]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU:", torch.cuda.get_device_name(0))
else:
    print("GPU not available, using CPU.")

GPU not available, using CPU.


In [6]:
# Using Rand
torch.rand(2,3)

tensor([[0.1980, 0.4212, 0.1269],
        [0.5176, 0.9199, 0.9553]])

In [7]:
# Use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.manual_seed(100)
torch.rand(4,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
#Using arange
print(torch.arange(0,10,2))

#Using linspace
print(torch.linspace(0,10,10))
print(torch.linspace(0,1,5))

#USING Eye
print(torch.eye(5))

# Using full
print(torch.full((3,3),7))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
